vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO chenjunfu2/NBT_CPP
    REF "v${VERSION}"
    HEAD_REF master
    SHA512 5e8ff1ee528b33da0cdc223ee360dfb6b0681d5b538f926bb173105a3a439a7a740d462263cbce3fe5ee8c7baa936441690299643f0b2007343f13a1f161c35b
)

# install
file(INSTALL "${SOURCE_PATH}/include/nbt_cpp/"
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/nbt_cpp"
     FILES_MATCHING
     PATTERN "*.hpp"
     PATTERN "*.h"
     PATTERN "vcpkg_config.h" EXCLUDE
)

# vcpkg_config
set(CONFIG_HEADER_CONTENT "#pragma once\n")
set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//Auto-generated by vcpkg - DO NOT EDIT\n\n")

if("zlib" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use zlib\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_ZLIB\n\n")
endif()

if("xxhash" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use xxhash\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_XXHASH\n\n")
endif()

file(WRITE "${CURRENT_PACKAGES_DIR}/include/nbt_cpp/vcpkg_config.h" "${CONFIG_HEADER_CONTENT}")

# copyright
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)